### ISSUE TITLE
Allow for local testing

### ISSUE THREAD

**Issue by mikeh2** [gradescope/gradescope-utils#6]
I realize this could be submitted as a pull request. 

FILE: gradescope-utils/gradescope_utils/autograder_utils/files.py:
ISSUE: SUBMISSION_BASE should be passed in as an default argument to allow local testing.

```
SUBMISSION_BASE = '/autograder/submission'
def check_submitted_files(paths, base=SUBMISSION_BASE):
...
    target_path = os.path.join(base, path)
...
```

**Comment by ibrahima** [comment]
Good suggestion, I would love to make it easier to test autograders locally.

**Comment by mikeh2** [comment]
any chance for this getting done?   It's literally only 2 lines of code to change.  Thanks so much

**Comment by ibrahima** [comment]
Done! Try installing v0.2.8, it should work there.

**Comment by mikeh2** [comment]
Thanks

I was looking for a way to set the __weight__ attribute myself in the unit test.

inside my one of my test methods
dir(getattr(self, self._testMethodName)) —> shows that __weight__ is there
BUT
setattr( of the above, '__weight__', 0.33) fails saying object has no attribute __weight__ 

Any chance you know what I am doing wrong ?

thanks so much!!

mike

**Comment by ibrahima** [comment]
Are you the Mike that wanted to set up partial credit for tests? I'm working on a decorator for that actually but I ran into some issues, but hopefully I can resolve them tomorrow!

**Comment by ibrahima** [comment]
I haven't actually tried your code above, but you may want to check this out: https://github.com/gradescope/gradescope-utils/pull/9 . I need to do a little more testing but it seems to work so far.

I would suggest that changing the weight of the test case dynamically is a little confusing, but would certainly achieve the goal of modifying the total score. But I think it's a little more informative to set the score rather than the weight because otherwise it's not clear what the maximum value is anymore, and as a student you won't be able to (easily) know whether you got the right answer.
